zuul:
  #  ignored-services: organizationservice
  ignored-services: "*"
  prefix: /api
  routes:
    organizationservice: /organization/**
    licensingservice: /licensing/**
    configserver: /configserver/**
    specialroutesservcie: /specialroutesservice/**
  sensitiveHeaders: Cookie,Set-Cookie
  debug:
    request: true

# 全局配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 15000

jwt:
  signing:
    key: ajwtsigningkey0123456789012345678
