server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:config/licensingservice/,classpath:config/organizationservice/,\
          classpath:config/zuulservice/,classpath:config/specialroutesservice/,classpath:config/orgservice-new/"
