server:
  port: 9004

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 设置日志记录级别
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.taoing.organizationservice: DEBUG

mybatis:
  mapper-locations: classpath:com/taoing/organizationservice/mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  type-aliases-package: com.taoing.organizationservice.model