zuul:
#  ignored-services: organizationservice
  ignored-services: "*"
  prefix: /api
  routes:
    organizationservice: /organization/**
    licensingservice: /licensing/**
    configserver: /configserver/**
