server:
  port: 8890
  servlet:
    context-path: /auth

logging:
  level:
    com.netflix: WARN
    org.springframework.web: INFO
    com.taoing: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/